import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "EAzEl Plot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
        <Toaster
          toastOptions={{
            classNames: {
              error: "!bg-red-600 !text-white !border-red-600",
              // success: "text-green-600", // 必要であれば他のタイプも同様に設定可能
              // warning: "text-yellow-600",
              // info: "text-blue-600",
            },
          }}
        />
      </body>
    </html>
  );
}
